/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package appointmentmanagementsystem;

import java.awt.event.MouseAdapter;
import java.awt.event.MouseEvent;
import java.util.ArrayList;
import java.util.List;
import java.util.stream.Collectors;
import javax.swing.DefaultComboBoxModel;
import javax.swing.JFrame;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author chris
 */
public class PatientRecord extends javax.swing.JPanel {

    private final JFrame prevFrame;
    private List<String> records = new ArrayList<>();
    private String[] headersForTable = {"Record Id", "Diagnosis", "Treatment", "Date"};
    /**
     * Creates new form PatientRecord
     * @param frame
     */
    public PatientRecord(JFrame frame) {
        this.prevFrame = frame;
        initComponents();
        
        List<String> data = AppointmentManagementSystem.getData(AppointmentManagementSystem.USER_TXT_FILE);
        data.remove(0);
        
        String[] model = data.stream().filter(item -> item.split(AppointmentManagementSystem.FILE_DELIMITER)[1].equalsIgnoreCase("PATIENT"))
                .map(item -> item.split(AppointmentManagementSystem.FILE_DELIMITER)[0] + ":" + item.split(AppointmentManagementSystem.FILE_DELIMITER)[2])
                .collect(Collectors.toList()).toArray(String[]::new);
        patientsCombo.setModel(new DefaultComboBoxModel<>(model));
        
        patientRecordsTable.addMouseListener(new MouseAdapter() {
            @Override
            public void mouseClicked(MouseEvent e){
                final int selectedRow = patientRecordsTable.getSelectedRow();
                final String record = records.get(selectedRow);
                final String[] recordById = AppointmentManagementSystem.getRecordById(record.split(AppointmentManagementSystem.FILE_DELIMITER)[0],AppointmentManagementSystem.PATIENTS_RECORDS_TXT_FILE);
                final String[] doctorRecord = AppointmentManagementSystem.getRecordById(recordById[2], AppointmentManagementSystem.USER_TXT_FILE);
               txtDate.setText(recordById[5]);
               txtDiagnosis.setText(recordById[3]);
               txtMedication.setText(recordById[4]);
               txtDoctor.setText(doctorRecord[2]);
            }});
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jSeparator1 = new javax.swing.JSeparator();
        txtSearch = new javax.swing.JTextField();
        btnAdd = new javax.swing.JButton();
        jLabel2 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        patientRecordsTable = new javax.swing.JTable();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        jScrollPane2 = new javax.swing.JScrollPane();
        txtMedication = new javax.swing.JTextArea();
        jScrollPane3 = new javax.swing.JScrollPane();
        txtDiagnosis = new javax.swing.JTextArea();
        jLabel6 = new javax.swing.JLabel();
        txtDate = new javax.swing.JTextField();
        txtDoctor = new javax.swing.JTextField();
        btnSearch = new javax.swing.JButton();
        btnSubmit = new javax.swing.JButton();
        patientsCombo = new javax.swing.JComboBox<>();
        jLabel10 = new javax.swing.JLabel();
        btnDate = new javax.swing.JButton();

        setBackground(new java.awt.Color(0, 51, 51));
        setMaximumSize(new java.awt.Dimension(1563, 885));
        setMinimumSize(new java.awt.Dimension(1563, 885));
        setPreferredSize(new java.awt.Dimension(1563, 885));

        jLabel1.setFont(new java.awt.Font("Monospaced", 0, 36)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setText("Patient Record");

        txtSearch.setBackground(new java.awt.Color(255, 255, 255));
        txtSearch.setFont(new java.awt.Font("Monospaced", 1, 18)); // NOI18N
        txtSearch.setForeground(new java.awt.Color(0, 0, 0));

        btnAdd.setBackground(new java.awt.Color(204, 102, 0));
        btnAdd.setFont(new java.awt.Font("Monospaced", 1, 18)); // NOI18N
        btnAdd.setText("Add new Recod");
        btnAdd.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAddActionPerformed(evt);
            }
        });

        jLabel2.setFont(new java.awt.Font("Monospaced", 0, 18)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(255, 255, 255));
        jLabel2.setText("Patient Email");

        patientRecordsTable.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Record Id", "Diagnosis", "Treatment", "Date"
            }
        ));
        jScrollPane1.setViewportView(patientRecordsTable);

        jLabel4.setFont(new java.awt.Font("Monospaced", 1, 24)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(255, 255, 255));
        jLabel4.setText("Details:");

        jLabel5.setFont(new java.awt.Font("Monospaced", 0, 18)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(255, 255, 255));
        jLabel5.setText("Date:");

        jLabel8.setFont(new java.awt.Font("Monospaced", 0, 18)); // NOI18N
        jLabel8.setForeground(new java.awt.Color(255, 255, 255));
        jLabel8.setText("Patient");
        jLabel8.setEnabled(false);
        jLabel8.setFocusable(false);

        jLabel9.setFont(new java.awt.Font("Monospaced", 0, 18)); // NOI18N
        jLabel9.setForeground(new java.awt.Color(255, 255, 255));
        jLabel9.setText("Diagnosis:");

        txtMedication.setBackground(new java.awt.Color(255, 255, 255));
        txtMedication.setColumns(20);
        txtMedication.setFont(new java.awt.Font("Monospaced", 0, 18)); // NOI18N
        txtMedication.setForeground(new java.awt.Color(0, 0, 0));
        txtMedication.setRows(5);
        jScrollPane2.setViewportView(txtMedication);

        txtDiagnosis.setBackground(new java.awt.Color(255, 255, 255));
        txtDiagnosis.setColumns(20);
        txtDiagnosis.setFont(new java.awt.Font("Monospaced", 0, 18)); // NOI18N
        txtDiagnosis.setForeground(new java.awt.Color(0, 0, 0));
        txtDiagnosis.setRows(5);
        jScrollPane3.setViewportView(txtDiagnosis);

        jLabel6.setFont(new java.awt.Font("Monospaced", 0, 18)); // NOI18N
        jLabel6.setForeground(new java.awt.Color(255, 255, 255));
        jLabel6.setText("Doctor");

        txtDate.setEditable(false);
        txtDate.setBackground(new java.awt.Color(255, 255, 255));
        txtDate.setFont(new java.awt.Font("Monospaced", 0, 18)); // NOI18N
        txtDate.setForeground(new java.awt.Color(0, 0, 0));

        txtDoctor.setEditable(false);
        txtDoctor.setBackground(new java.awt.Color(255, 255, 255));
        txtDoctor.setFont(new java.awt.Font("Monospaced", 0, 18)); // NOI18N
        txtDoctor.setForeground(new java.awt.Color(0, 0, 0));

        btnSearch.setBackground(new java.awt.Color(204, 102, 0));
        btnSearch.setFont(new java.awt.Font("Monospaced", 1, 18)); // NOI18N
        btnSearch.setText("Search");
        btnSearch.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSearchActionPerformed(evt);
            }
        });

        btnSubmit.setBackground(new java.awt.Color(204, 102, 0));
        btnSubmit.setFont(new java.awt.Font("Monospaced", 1, 18)); // NOI18N
        btnSubmit.setText("Submit");
        btnSubmit.setEnabled(false);
        btnSubmit.setFocusable(false);
        btnSubmit.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSubmitActionPerformed(evt);
            }
        });

        patientsCombo.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));
        patientsCombo.setEnabled(false);
        patientsCombo.setFocusable(false);
        patientsCombo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                patientsComboActionPerformed(evt);
            }
        });

        jLabel10.setFont(new java.awt.Font("Monospaced", 0, 18)); // NOI18N
        jLabel10.setForeground(new java.awt.Color(255, 255, 255));
        jLabel10.setText("Medication");

        btnDate.setBackground(new java.awt.Color(0, 0, 0));
        btnDate.setFont(new java.awt.Font("Monospaced", 1, 15)); // NOI18N
        btnDate.setForeground(new java.awt.Color(255, 255, 255));
        btnDate.setText("select");
        btnDate.setToolTipText("");
        btnDate.setEnabled(false);
        btnDate.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnDateActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(16, 16, 16)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 561, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                    .addComponent(txtSearch, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, 301, Short.MAX_VALUE)
                                    .addComponent(jSeparator1, javax.swing.GroupLayout.Alignment.LEADING))
                                .addGap(18, 18, 18)
                                .addComponent(btnSearch, javax.swing.GroupLayout.PREFERRED_SIZE, 110, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 633, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 135, Short.MAX_VALUE))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel2)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jLabel8)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel4)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(btnAdd, javax.swing.GroupLayout.PREFERRED_SIZE, 224, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(jLabel9)
                    .addComponent(jScrollPane3)
                    .addComponent(jScrollPane2)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel6)
                            .addComponent(jLabel5))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(txtDoctor, javax.swing.GroupLayout.PREFERRED_SIZE, 427, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(txtDate, javax.swing.GroupLayout.PREFERRED_SIZE, 326, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(btnDate))))
                    .addComponent(btnSubmit, javax.swing.GroupLayout.PREFERRED_SIZE, 224, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(patientsCombo, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(280, 280, 280))
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                    .addContainerGap(794, Short.MAX_VALUE)
                    .addComponent(jLabel10)
                    .addGap(659, 659, 659)))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(19, 19, 19)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                        .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 52, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jSeparator1, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(36, 36, 36)
                        .addComponent(jLabel2)
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(txtSearch, javax.swing.GroupLayout.PREFERRED_SIZE, 47, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(btnSearch, javax.swing.GroupLayout.PREFERRED_SIZE, 47, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(71, 71, 71)
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(btnAdd, javax.swing.GroupLayout.PREFERRED_SIZE, 47, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                .addComponent(jLabel5)
                                .addComponent(txtDate, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addComponent(btnDate))
                        .addGap(26, 26, 26)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel6)
                            .addComponent(txtDoctor, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addComponent(jLabel9)
                        .addGap(18, 18, 18)
                        .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, 167, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(52, 52, 52)
                        .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 207, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jLabel8)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(patientsCombo, javax.swing.GroupLayout.PREFERRED_SIZE, 38, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(btnSubmit, javax.swing.GroupLayout.PREFERRED_SIZE, 47, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(92, Short.MAX_VALUE))
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(layout.createSequentialGroup()
                    .addGap(419, 419, 419)
                    .addComponent(jLabel10)
                    .addContainerGap(444, Short.MAX_VALUE)))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void btnAddActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAddActionPerformed
        patientsCombo.setEnabled(!patientsCombo.isEnabled());
        btnSubmit.setEnabled(!btnSubmit.isEnabled());
        btnDate.setEnabled(!btnDate.isEnabled());
        txtDate.setText("");
        txtDiagnosis.setText("");
        txtMedication.setText("");
        txtDoctor.setText(btnSubmit.isEnabled() ? AppointmentManagementSystem.loggedInUserId + ":" + AppointmentManagementSystem.loggedInUserName : "");
    }//GEN-LAST:event_btnAddActionPerformed

    private void btnSearchActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSearchActionPerformed
        if(!txtSearch.getText().isEmpty()) {
            initializeTable();
        }
    }//GEN-LAST:event_btnSearchActionPerformed

    private void btnSubmitActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSubmitActionPerformed
        final int nextId = AppointmentManagementSystem.getNextId(AppointmentManagementSystem.PATIENTS_RECORDS_TXT_FILE);
        
        final String patientID = patientsCombo.getSelectedItem().toString().split(":")[0];
        final String[] patient = AppointmentManagementSystem.getRecordById(patientID, AppointmentManagementSystem.USER_TXT_FILE);
        
        
        String newRecord = "\n" + nextId + AppointmentManagementSystem.FILE_DELIMITER +
                patientID + AppointmentManagementSystem.FILE_DELIMITER +
                AppointmentManagementSystem.loggedInUserId + AppointmentManagementSystem.FILE_DELIMITER +
                txtDiagnosis.getText() + AppointmentManagementSystem.FILE_DELIMITER +
                txtMedication.getText() + AppointmentManagementSystem.FILE_DELIMITER +
                txtDate.getText() + AppointmentManagementSystem.FILE_DELIMITER + 
                patient[6];
        
        final boolean isSaved = AppointmentManagementSystem.writeLineToFile(AppointmentManagementSystem.PATIENTS_RECORDS_TXT_FILE, newRecord);
        
        if (isSaved) {
            JOptionPane.showMessageDialog(null, "Record saved successfully");
        } else {
            JOptionPane.showConfirmDialog(null, "Error saving record");
        }
        
    }//GEN-LAST:event_btnSubmitActionPerformed

    private void btnDateActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnDateActionPerformed
        txtDate.setText(new DatePicker(prevFrame).setPickedDate());
    }//GEN-LAST:event_btnDateActionPerformed

    private void patientsComboActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_patientsComboActionPerformed
         
    }//GEN-LAST:event_patientsComboActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnAdd;
    private javax.swing.JButton btnDate;
    private javax.swing.JButton btnSearch;
    private javax.swing.JButton btnSubmit;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JTable patientRecordsTable;
    private javax.swing.JComboBox<String> patientsCombo;
    private javax.swing.JTextField txtDate;
    private javax.swing.JTextArea txtDiagnosis;
    private javax.swing.JTextField txtDoctor;
    private javax.swing.JTextArea txtMedication;
    private javax.swing.JTextField txtSearch;
    // End of variables declaration//GEN-END:variables

    private void initializeTable() {
        records = AppointmentManagementSystem.getData(AppointmentManagementSystem.PATIENTS_RECORDS_TXT_FILE);

        if (records.isEmpty()) {

        } else {
            records.remove(0); // remove the headersForAppointmentTable
            if (records.isEmpty()) {

            } else {

                records = records.stream().filter(item -> item.split(AppointmentManagementSystem.FILE_DELIMITER)[6].equals(txtSearch.getText()) && !item.isEmpty())
                        .collect(Collectors.toList());
                
                String[][] tableData = new String[records.size()][headersForTable.length];

                int[] count = {0};
                records.forEach(item -> {
                    String[] i = item.split(AppointmentManagementSystem.FILE_DELIMITER);
                    tableData[count[0]][0] = i[0]; // record id
                    tableData[count[0]][1] = i[3]; // diagnosis
                    tableData[count[0]][2] = i[4]; // medication
                    tableData[count[0]][3] = i[5]; // date

                    // between dates
                    count[0] += 1;
                });

                DefaultTableModel model = new DefaultTableModel(tableData, headersForTable);
                patientRecordsTable.setModel(model);
            }
        }
    }
}
